name: gh

on:
  create:  # is used for publishing to PyPI and TestPyPI
    tags:  # any tag regardless of its name, no branches
  push:  # only publishes pushes to the main branch to TestPyPI
    branches:  # any maintenance branch but not tag
      # avoid generic ** as it duplicates builds from temporary branches
      - "master"
      - "stable/**"
    tags-ignore:
    - >-
      **
  pull_request:

jobs:
  build_python:
    name: ${{ matrix.name }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          - name: linting
            python-version: 3.6
          - name: py36
            python-version: 3.6
          - name: py37
            python-version: 3.7
          - name: py38
            python-version: 3.8
          - name: py39
            python-version: 3.9
          - name: devel
            python-version: 3.8
          - name: pypy3
            python-version: pypy3
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix['python-version'] }}
    - name: Install tox
      run: |
        python -m pip install --upgrade tox
    - name: Test with tox
      run: |
        python -m tox -e ${{ matrix.name }}
  build_javascript:
    name: javascript
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Dependencies
      run: |
        npm install phantomjs-prebuilt@2.1.15 grunt-cli grunt grunt-contrib-qunit
    - name: QUnit Tests
      run: |
        grunt test
      env:
        CI: true
